version: "3.8"

services:
  db:
    image: mysql:8.0.22
    volumes:
      - db-data:/var/lib/mysql/
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  
  backend:
    build:
      context: ./backend
      args: 
        WORKDIR: $WORKDIR
    volumes:
      - ./backend:/$WORKDIR
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      API_DOMAIN: "localhost:$FRONTEND_PORT"
    ports:
      - "$BACKEND_PORT:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend
      args: 
        WORKDIR: $WORKDIR
    volumes:
      - ./frontend:/$WORKDIR
    command: yarn serve
    ports:
      - "$FRONTEND_PORT:8080"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  db-data:
